Repository MarkelFe/metacritic-crawler, pull requests merged in 2019-03, with the labels that each got.

#21 abstract extract_value function; replace extract/extract_first with get/getall
  analyze.py
  games.py
Labels: enhancement

#23 README update
  README.md
  docs/flags.md
Labels: enhancement

#20 Create requirements.txt
  requirements.txt
Labels: WIP

#22 Loading bar
  .gitignore
  analyze.py
Labels: enhancement

#25 Travis CI
  .travis.yml
  README.md
Labels: enhancement

#26 Don't crawl incoming games
  games.py
Labels: bug, enhancement

#27 fix spelling and make docs more succinct
  README.md
  docs/flags.md
Labels: WIP, enhancement

#29 Basic load "bar"
  games.py
Labels: enhancement, help wanted

#30 Load bar
  games.py
Labels: enhancement
